# Generated by Django 3.2.5 on 2023-10-27 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20231026_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 16, 37, 25, 931996, tzinfo=utc)),
        ),
    ]
