# Generated by Django 3.2.5 on 2023-10-31 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_brandprofile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 7, 49, 43, 265009, tzinfo=utc)),
        ),
    ]
