# Generated by Django 3.2.5 on 2023-10-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branduser',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
