# Generated by Django 3.2.5 on 2023-10-25 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20231025_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branduser',
            name='token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='token',
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 14, 18, 45, 415493, tzinfo=utc)),
        ),
    ]
