# Generated by Django 3.2.5 on 2023-10-25 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20231025_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 15, 1, 51, 345613, tzinfo=utc)),
        ),
    ]
