# Generated by Django 3.2.5 on 2023-10-19 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_branduser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='brand_bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='brand_logo',
            field=models.ImageField(default='', upload_to='Brand Logos'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='brand_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='brand_type',
            field=models.CharField(choices=[('Clothing and Apparel', 'Clothing and Apparel'), ('Accessories', 'Accessories'), ('Arts', 'Arts'), ('Footwears & Canvas', 'Footwears & Canvas')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 9, 29, 37, 867337, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='followers',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
