# Generated by Django 3.2.5 on 2023-10-27 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_brandprofile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 16, 53, 11, 640238, tzinfo=utc)),
        ),
    ]
