# Generated by Django 3.2.5 on 2023-10-31 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20231031_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 8, 11, 1, 67666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to='account.branduser'),
        ),
    ]
