version: '3.8'
services:
  web:
    build: .
    command: gunicorn altclan.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://altclan_eh2g_user:MM6uIMm8tqqrRBop8y5PufZUucIE4voP@dpg-cvt7ifqdbo4c73cjitjg-a.oregon-postgres.render.com/altclan_eh2g
