version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=altclan
      - POSTGRES_USER=altclan_user
      - POSTGRES_PASSWORD=Gridlock10%