version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: altclan_hk5s
      POSTGRES_USER: altclan_hk5s_user
      POSTGRES_PASSWORD: EDNRA5OZ1rguW6Cj0xqoWDVpmuLAaMJr
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - POSTGRES_DB=altclan_hk5s
      - POSTGRES_USER=altclan_hk5s_user
      - POSTGRES_PASSWORD=EDNRA5OZ1rguW6Cj0xqoWDVpmuLAaMJr
      - POSTGRES_HOST=dpg-csvco7jtq21c73emtkh0-a.oregon-postgres.render.com
      - POSTGRES_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: