services:
  - name: altclan-api
    type: web
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVarGroups:
      - altclan-production  # Reference to environment group created in Render dashboard
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: altclan.settings