# Generated by Django 3.2.5 on 2023-10-26 10:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(default='', max_length=250)),
                ('city', models.CharField(default='', max_length=250)),
                ('state', models.CharField(default='', max_length=250)),
                ('zip', models.CharField(default='', max_length=250)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='account.branduser')),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=250, null=True)),
                ('website_link', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(default='', max_length=250)),
                ('city', models.CharField(default='', max_length=250)),
                ('state', models.CharField(default='', max_length=250)),
                ('zip', models.CharField(default='', max_length=250)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchandise_name', models.CharField(default='', max_length=250)),
                ('merchandise_color', models.CharField(default='', max_length=250)),
                ('merchandise_size', models.CharField(default='', max_length=250)),
                ('display_image', models.ImageField(default='', upload_to='Merch Image')),
                ('available_color_1', models.CharField(blank=True, max_length=250, null=True)),
                ('available_color_2', models.CharField(blank=True, max_length=250, null=True)),
                ('available_color_3', models.CharField(blank=True, max_length=250, null=True)),
                ('image_1', models.ImageField(blank=True, default='', null=True, upload_to='Merch Image')),
                ('image_2', models.ImageField(blank=True, default='', null=True, upload_to='Merch Image')),
                ('image_3', models.ImageField(blank=True, default='', null=True, upload_to='Merch Image')),
                ('image_4', models.ImageField(blank=True, default='', null=True, upload_to='Merch Image')),
                ('image_5', models.ImageField(blank=True, default='', null=True, upload_to='Merch Image')),
                ('labels', models.CharField(choices=[('None', 'None'), ('New Merchandise', 'New Merchandise'), ('Limited Stock', 'Limited Stock'), ('FREE DELIVERY', 'FREE DELIVERY')], default='', max_length=250)),
                ('price', models.CharField(default='', max_length=250)),
                ('delivery_cost', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('discount', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('category', models.CharField(blank=True, choices=[('Tops', 'Tops'), ('Pants', 'Pants'), ('Sweaters', 'Sweaters'), ('T-Shirts', 'T-Shirts'), ('Jackets', 'Jackets'), ('Denim', 'Denim'), ('Sweaters', 'Sweaters'), ('Watches', 'Watches'), ('Wallets', 'Wallets'), ('Bags', 'Bags'), ('Sunglasses', 'Sunglasses'), ('Hats and Caps', 'Hats and Caps'), ('Belts', 'Belts')], default='', max_length=250, null=True)),
                ('slug', models.SlugField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 10, 26, 10, 56, 47, 199427, tzinfo=utc))),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.branduser')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.billingaddress')),
                ('merchandises', models.ManyToManyField(to='brands.Merchandise')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrandDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.CharField(blank=True, max_length=250, null=True)),
                ('total_users', models.CharField(blank=True, max_length=250, null=True)),
                ('total_products', models.CharField(blank=True, max_length=250, null=True)),
                ('total_profit', models.CharField(blank=True, max_length=250, null=True)),
                ('total_revenue', models.CharField(blank=True, max_length=250, null=True)),
                ('total_sales', models.CharField(blank=True, max_length=250, null=True)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_dashboard', to='account.brandprofile')),
            ],
        ),
    ]
