# Generated by Django 3.2.5 on 2023-10-31 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 7, 35, 39, 825188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='delivery_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
