# Generated by Django 4.2 on 2025-01-14 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 22, 34, 32, 529891, tzinfo=datetime.timezone.utc)),
        ),
    ]
