# Generated by Django 4.2 on 2025-08-02 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 23, 38, 16, 682183, tzinfo=datetime.timezone.utc)),
        ),
    ]
