# Generated by Django 3.2.5 on 2023-10-31 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20231031_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='category',
            field=models.CharField(blank=True, choices=[('Choose your desired collection', 'Choose your desired collection'), ('Tees', 'Tees'), ('Rings', 'Rings'), ('Joggers and Track', 'Joggers and Track'), ('Chains & Necklaces', 'Chains & Necklaces'), ('Jeans', 'Jeans'), ('Jackets', 'Jackets'), ('Skating', 'Skating'), ('Caps and Hats', 'Caps and Hats'), ('Skating', 'Skating'), ('Sweatshirts and Hoodies', 'Sweatshirts and Hoodies'), ('Kicks and Slides', 'Kicks and Slides'), ('Masks', 'Masks'), ('Shades', 'Shades'), ('Lumberjacks and Vintage', 'Lumberjacks and Vintage'), ('Piercings and Studs', 'Piercings and Studs'), ('Baggy Wears', 'Baggy Wears'), ('Tattoos', 'Tattoos'), ('Graffiti', 'Graffiti')], default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 7, 49, 43, 269641, tzinfo=utc)),
        ),
    ]
