# Generated by Django 3.2.5 on 2023-10-27 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_brandprofile_date_created'),
        ('brands', '0002_alter_merchandise_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branddashboard',
            name='profile',
        ),
        migrations.AddField(
            model_name='branddashboard',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_dashboard', to='account.branduser'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 16, 37, 25, 933004, tzinfo=utc)),
        ),
    ]
