# Generated by Django 4.2 on 2025-01-04 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_merchandise_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 4, 23, 30, 32, 98921, tzinfo=datetime.timezone.utc)),
        ),
    ]
