# Generated by Django 3.2.5 on 2023-10-09 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20231005_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='category',
            field=models.CharField(blank=True, choices=[('Tops', 'Tops'), ('Pants', 'Pants'), ('Sweaters', 'Sweaters'), ('T-Shirts', 'T-Shirts'), ('Jackets', 'Jackets'), ('Denim', 'Denim'), ('Sweaters', 'Sweaters'), ('Watches', 'Watches'), ('Wallets', 'Wallets'), ('Bags', 'Bags'), ('Sunglasses', 'Sunglasses'), ('Hats and Caps', 'Hats and Caps'), ('Belts', 'Belts')], default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 17, 7, 10, 951549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 17, 7, 10, 951549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 17, 7, 10, 966558, tzinfo=utc)),
        ),
    ]
