# Generated by Django 3.2.5 on 2023-10-27 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20231027_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 16, 53, 11, 641239, tzinfo=utc)),
        ),
    ]
