# Generated by Django 3.2.5 on 2023-10-31 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20231031_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 8, 10, 8, 187335, tzinfo=utc)),
        ),
    ]
