# Generated by Django 3.2.5 on 2023-09-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20230913_1901'),
        ('brands', '0004_auto_20230816_0406'),
    ]

    operations = [
    ]
