# Generated by Django 3.2.5 on 2023-10-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20231009_1807'),
        ('brands', '0005_merge_0003_auto_20230913_1901_0004_auto_20230816_0406'),
    ]

    operations = [
    ]
