# Generated by Django 3.2.5 on 2024-05-07 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_alter_merchandise_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='merchandises',
            new_name='colors',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='WishList Images'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 19, 14, 19, 700445, tzinfo=utc)),
        ),
    ]
