# Generated by Django 3.2.5 on 2023-10-12 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_merge_20231012_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchandisegallery',
            old_name='merchandise',
            new_name='merchandise_name',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.merchandisegallery'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 14, 46, 13, 129568, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 14, 46, 13, 129568, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 14, 46, 13, 133565, tzinfo=utc)),
        ),
    ]
