# Generated by Django 3.2.5 on 2023-10-12 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_auto_20231012_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 15, 1, 40, 221166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 15, 1, 40, 221166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 15, 1, 40, 225785, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='MerchandiseColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_color_1', models.CharField(blank=True, max_length=250, null=True)),
                ('available_color_2', models.CharField(blank=True, max_length=250, null=True)),
                ('available_color_3', models.CharField(blank=True, max_length=250, null=True)),
                ('available_color_4', models.CharField(blank=True, max_length=250, null=True)),
                ('merchandise', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchandise_gallery_color', to='brands.merchandise')),
            ],
        ),
    ]
