# Generated by Django 3.2.5 on 2024-05-07 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_auto_20240507_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 19, 52, 8, 779518, tzinfo=utc)),
        ),
    ]
