# Generated by Django 3.2.5 on 2024-05-07 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_alter_merchandise_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 19, 57, 59, 755079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_email',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
