# Generated by Django 3.2.5 on 2023-10-12 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_auto_20231012_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='available_color_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='available_color_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='available_color_3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 15, 6, 34, 240843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 15, 6, 34, 240843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 15, 6, 34, 240843, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='MerchandiseColor',
        ),
    ]
