# Generated by Django 3.2.5 on 2023-10-16 05:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0013_auto_20231016_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 27, 21, 756965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 27, 21, 756965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='gallery',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.merchandisegallery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 27, 21, 756965, tzinfo=utc)),
        ),
    ]
