# Generated by Django 3.2.5 on 2023-10-16 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0016_auto_20231016_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandisegallery',
            name='merchandise_name',
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 31, 9, 192210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 31, 9, 192210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 31, 9, 192210, tzinfo=utc)),
        ),
    ]
