# Generated by Django 3.2.5 on 2023-10-16 05:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0018_auto_20231016_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandisegallery',
            name='merchandise_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.merchandise'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 35, 20, 807387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 35, 20, 807387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='gallery',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchandise_gallery', to='brands.merchandisegallery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 35, 20, 807387, tzinfo=utc)),
        ),
    ]
