# Generated by Django 3.2.5 on 2023-10-16 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0020_auto_20231016_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='gallery',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='image_1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Merch Image'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='image_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Merch Image'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='image_3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Merch Image'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='image_4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Merch Image'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='image_5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Merch Image'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='image_6',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Merch Image'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 57, 30, 898313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 57, 30, 898313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 5, 57, 30, 898313, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='MerchandiseGallery',
        ),
    ]
