# Generated by Django 4.2 on 2025-01-11 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_brandprofile_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='orders',
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 4, 14, 2, 746399, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 4, 14, 2, 746399, tzinfo=datetime.timezone.utc)),
        ),
    ]
