# Generated by Django 4.2 on 2025-02-15 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountuser_orders_alter_profile_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 7, 39, 40, 202742, tzinfo=datetime.timezone.utc)),
        ),
    ]
