# Generated by Django 4.2 on 2025-01-04 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_brandprofile_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 4, 12, 20, 34, 695061, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 4, 12, 20, 34, 694078, tzinfo=datetime.timezone.utc)),
        ),
    ]
