# Generated by Django 4.2 on 2025-01-11 05:11

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_alter_billingaddress_user_and_more'),
        ('accounts', '0004_alter_brandprofile_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='brand_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='followers',
            new_name='following',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='brand_bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='brand_logo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='brand_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Display Picture'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orders',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='billing_address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zip',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 11, 5, 11, 13, 656934, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='BrandProfile',
        ),
        migrations.DeleteModel(
            name='BrandUser',
        ),
    ]
