# Generated by Django 3.2.5 on 2024-07-19 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20240719_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='branduser',
            name='shipping_address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 16, 12, 45, 994166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 16, 12, 45, 993734, tzinfo=utc)),
        ),
    ]
