# Generated by Django 3.2.5 on 2024-07-19 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20240719_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address',
            new_name='billing_address',
        ),
        migrations.RemoveField(
            model_name='branduser',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 16, 35, 29, 747182, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 16, 35, 29, 747182, tzinfo=utc)),
        ),
    ]
