# Generated by Django 4.2 on 2025-08-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField()),
                ('review', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
