# Generated by Django 3.2.5 on 2024-05-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.AddField(
            model_name='reviews',
            name='user_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
